# Generated by Django 6.0 on 2025-12-27 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermitProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Proje Adı")),
                ("description", models.TextField(verbose_name="Proje Detayı")),
                (
                    "applicant_name",
                    models.CharField(max_length=100, verbose_name="Başvuru Yapan"),
                ),
                (
                    "document_url",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Proje Dosyası Linki",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Başvuru Yapıldı"),
                            ("under_review", "İncelemede"),
                            ("approved", "Onaylandı"),
                            ("rejected", "Reddedildi"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "engineer_comments",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mühendis Yorumu"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_engineer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "staff"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
