# Generated by Django 6.0 on 2025-12-27 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Şikayet Başlığı"),
                ),
                ("description", models.TextField(verbose_name="Şikayet Detayı")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="complaints/",
                        verbose_name="Fotoğraf",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Konum (Opsiyonel)",
                    ),
                ),
                (
                    "assigned_unit",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Atanan Birim",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("assigned", "İlgili Birime Atandı"),
                            ("resolved", "Çözüldü"),
                            ("rejected", "Reddedildi"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "ai_analysis_result",
                    models.TextField(
                        blank=True, null=True, verbose_name="Yapay Zeka Analizi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
